#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_color    '#22272e'
bspc config focused_border_color    '#a97594'

#bspc rule -a spotify desktop='^0' focus=on

systemctl --user import-environment DISPLAY
xsetroot -cursor_name left_ptr
feh --bg-scale ~/.config/bspwm/fondo.jpg
